### ISSUE TITLE
On T4 GPU CUDA out of memory

### ISSUE THREAD

**Issue by 2994dd42d75b0** [GSeanCDAT/GIMM-VFI#6]
Traceback (most recent call last):
  File "/content/GIMM-VFI/./src/video_Nx.py", line 159, in <module>
    all_outputs = model(xs, coord_inputs, t=timesteps, ds_factor=ds_factor)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/GIMM-VFI/src/models/generalizable_INR/gimmvfi_r.py", line 348, in forward
    ) = self.cal_bidirection_flow(
  File "/content/GIMM-VFI/src/models/generalizable_INR/gimmvfi_r.py", line 133, in cal_bidirection_flow
    corr_fn = BidirCorrBlock(self.amt_fproj(fnet0), self.amt_fproj(fnet1), radius=4)
  File "/content/GIMM-VFI/src/models/generalizable_INR/raft/corr.py", line 42, in __init__
    corr_T = F.avg_pool2d(corr_T, 2, stride=2)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.97 GiB. GPU 0 has a total capacity of 14.75 GiB of which 3.43 GiB is free. Process 94276 has 11.31 GiB memory in use. Of the allocated memory 10.72 GiB is allocated by PyTorch, and 478.01 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by 2994dd42d75b0** [comment]
Thanks Working Now
